# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/dave/ip/examples/framebuffer_test/framebuffer_test.srcs/sources_1/ip/output_line_buffer_1/output_line_buffer.xci
# IP: The module: 'output_line_buffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dave/ip/examples/framebuffer_test/framebuffer_test.srcs/sources_1/ip/output_line_buffer_1/output_line_buffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'output_line_buffer'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/dave/ip/examples/framebuffer_test/framebuffer_test.srcs/sources_1/ip/output_line_buffer_1/output_line_buffer.xci
# IP: The module: 'output_line_buffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dave/ip/examples/framebuffer_test/framebuffer_test.srcs/sources_1/ip/output_line_buffer_1/output_line_buffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'output_line_buffer'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
