# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k325tffg900-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/dave/ip/examples/ov13850_demo/ov13850_demo.cache/wt [current_project]
set_property parent.project_path /home/dave/ip/examples/ov13850_demo/ov13850_demo.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/dave/ip/examples/ov13850_demo/ov13850_demo.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files -quiet /home/dave/ip/examples/ov13850_demo/ov13850_demo.srcs/sources_1/ip/input_line_buffer_1/input_line_buffer.dcp
set_property used_in_implementation false [get_files /home/dave/ip/examples/ov13850_demo/ov13850_demo.srcs/sources_1/ip/input_line_buffer_1/input_line_buffer.dcp]
add_files -quiet /home/dave/ip/examples/ov13850_demo/ov13850_demo.srcs/sources_1/ip/output_line_buffer_1/output_line_buffer.dcp
set_property used_in_implementation false [get_files /home/dave/ip/examples/ov13850_demo/ov13850_demo.srcs/sources_1/ip/output_line_buffer_1/output_line_buffer.dcp]
add_files -quiet /home/dave/ip/examples/ov13850_demo/ov13850_demo.srcs/sources_1/ip/dvi_pll_1/dvi_pll.dcp
set_property used_in_implementation false [get_files /home/dave/ip/examples/ov13850_demo/ov13850_demo.srcs/sources_1/ip/dvi_pll_1/dvi_pll.dcp]
add_files -quiet /home/dave/ip/examples/ov13850_demo/ov13850_demo.srcs/sources_1/ip/camera_pll_1/camera_pll.dcp
set_property used_in_implementation false [get_files /home/dave/ip/examples/ov13850_demo/ov13850_demo.srcs/sources_1/ip/camera_pll_1/camera_pll.dcp]
add_files -quiet /home/dave/ip/examples/ov13850_demo/ov13850_demo.srcs/sources_1/ip/ddr3_if_1/ddr3_if.dcp
set_property used_in_implementation false [get_files /home/dave/ip/examples/ov13850_demo/ov13850_demo.srcs/sources_1/ip/ddr3_if_1/ddr3_if.dcp]
read_vhdl -library xil_defaultlib {
  /home/dave/ip/mipi-csi-rx/csi_rx_line_buffer.vhd
  /home/dave/ip/mipi-csi-rx/csi_rx_word_align.vhd
  /home/dave/ip/mipi-csi-rx/csi_rx_idelayctrl_gen.vhd
  /home/dave/ip/mipi-csi-rx/csi_rx_hs_lane_phy.vhd
  /home/dave/ip/mipi-csi-rx/csi_rx_hs_clk_phy.vhd
  /home/dave/ip/mipi-csi-rx/csi_rx_hdr_ecc.vhd
  /home/dave/ip/mipi-csi-rx/csi_rx_clock_det.vhd
  /home/dave/ip/mipi-csi-rx/csi_rx_byte_align.vhd
  /home/dave/ip/video-misc/video_timing_ctrl.vhd
  /home/dave/ip/framebuffer-ctrl/framebuffer_ctrl.vhd
  /home/dave/ip/dvi-tx/dvi_tx_tmds_phy.vhd
  /home/dave/ip/dvi-tx/dvi_tx_tmds_enc.vhd
  /home/dave/ip/dvi-tx/dvi_tx_clk_drv.vhd
  /home/dave/ip/mipi-csi-rx/csi_rx_video_output.vhd
  /home/dave/ip/mipi-csi-rx/csi_rx_packet_handler.vhd
  /home/dave/ip/mipi-csi-rx/csi_rx_4_lane_link.vhd
  /home/dave/ip/mipi-csi-rx/csi_rx_10bit_unpack.vhd
  /home/dave/ip/video-misc/video_fb_output.vhd
  /home/dave/ip/ov-cam-control/ov_i2c_control.vhd
  /home/dave/ip/ov-cam-control/ov13850_4k_regs.vhd
  /home/dave/ip/dvi-tx/dvi_tx_top.vhd
  /home/dave/ip/mipi-csi-rx/csi_rx_top.vhd
  /home/dave/ip/demo-top/framebuffer_top.vhd
  /home/dave/ip/video-misc/image_gain_wb.vhd
  /home/dave/ip/video-misc/simple_debayer.vhd
  /home/dave/ip/ov-cam-control/ov13850_control_top.vhd
  /home/dave/ip/demo-top/ov13850_demo.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/dave/ip/examples/ov13850_demo/ov13850_demo.srcs/constrs_1/imports/new/genesys2.xdc
set_property used_in_implementation false [get_files /home/dave/ip/examples/ov13850_demo/ov13850_demo.srcs/constrs_1/imports/new/genesys2.xdc]

read_xdc /home/dave/ip/examples/ov13850_demo/ov13850_demo.srcs/constrs_1/imports/constraints/ddr3_if.xdc
set_property used_in_implementation false [get_files /home/dave/ip/examples/ov13850_demo/ov13850_demo.srcs/constrs_1/imports/constraints/ddr3_if.xdc]


synth_design -top ov13850_demo -part xc7k325tffg900-2 -retiming


write_checkpoint -force -noxdef ov13850_demo.dcp

catch { report_utilization -file ov13850_demo_utilization_synth.rpt -pb ov13850_demo_utilization_synth.pb }
