# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k325tffg900-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/dave/ip/examples/dvi_test/dvi_test.cache/wt [current_project]
set_property parent.project_path /home/dave/ip/examples/dvi_test/dvi_test.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo /home/dave/ip/examples/dvi_test/dvi_test.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files -quiet /home/dave/ip/examples/dvi_test/dvi_test.srcs/sources_1/ip/hdmi_pll/hdmi_pll.dcp
set_property used_in_implementation false [get_files /home/dave/ip/examples/dvi_test/dvi_test.srcs/sources_1/ip/hdmi_pll/hdmi_pll.dcp]
read_vhdl -library xil_defaultlib {
  /home/dave/ip/dvi-tx/dvi_tx_tmds_phy.vhd
  /home/dave/ip/dvi-tx/dvi_tx_tmds_enc.vhd
  /home/dave/ip/dvi-tx/dvi_tx_clk_drv.vhd
  /home/dave/ip/examples/dvi_test/dvi_test.srcs/sources_1/new/test_pattern_1080p.vhd
  /home/dave/ip/dvi-tx/dvi_tx_top.vhd
  /home/dave/ip/examples/dvi_test/dvi_test.srcs/sources_1/new/genesys2_hdmitest.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/dave/ip/examples/dvi_test/dvi_test.srcs/constrs_1/new/genesys2.xdc
set_property used_in_implementation false [get_files /home/dave/ip/examples/dvi_test/dvi_test.srcs/constrs_1/new/genesys2.xdc]


synth_design -top genesys2_hdmitest -part xc7k325tffg900-2


write_checkpoint -force -noxdef genesys2_hdmitest.dcp

catch { report_utilization -file genesys2_hdmitest_utilization_synth.rpt -pb genesys2_hdmitest_utilization_synth.pb }
