# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/dave/ip/examples/dvi_test/dvi_test.srcs/sources_1/ip/hdmi_pll/hdmi_pll.xci
# IP: The module: 'hdmi_pll' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dave/ip/examples/dvi_test/dvi_test.srcs/sources_1/ip/hdmi_pll/hdmi_pll_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_pll'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/dave/ip/examples/dvi_test/dvi_test.srcs/sources_1/ip/hdmi_pll/hdmi_pll.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/dave/ip/examples/dvi_test/dvi_test.srcs/sources_1/ip/hdmi_pll/hdmi_pll_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /home/dave/ip/examples/dvi_test/dvi_test.srcs/sources_1/ip/hdmi_pll/hdmi_pll.xci
# IP: The module: 'hdmi_pll' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dave/ip/examples/dvi_test/dvi_test.srcs/sources_1/ip/hdmi_pll/hdmi_pll_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/dave/ip/examples/dvi_test/dvi_test.srcs/sources_1/ip/hdmi_pll/hdmi_pll.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/dave/ip/examples/dvi_test/dvi_test.srcs/sources_1/ip/hdmi_pll/hdmi_pll_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
