# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/dave/ip/examples/ov13850_demo/ov13850_demo.srcs/sources_1/ip/camera_pll_1/camera_pll.xci
# IP: The module: 'camera_pll' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dave/ip/examples/ov13850_demo/ov13850_demo.srcs/sources_1/ip/camera_pll_1/camera_pll_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'camera_pll'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/dave/ip/examples/ov13850_demo/ov13850_demo.srcs/sources_1/ip/camera_pll_1/camera_pll.xdc
# XDC: The top module name and the constraint reference have the same name: 'camera_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/dave/ip/examples/ov13850_demo/ov13850_demo.srcs/sources_1/ip/camera_pll_1/camera_pll_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'camera_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /home/dave/ip/examples/ov13850_demo/ov13850_demo.srcs/sources_1/ip/camera_pll_1/camera_pll.xci
# IP: The module: 'camera_pll' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dave/ip/examples/ov13850_demo/ov13850_demo.srcs/sources_1/ip/camera_pll_1/camera_pll_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'camera_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/dave/ip/examples/ov13850_demo/ov13850_demo.srcs/sources_1/ip/camera_pll_1/camera_pll.xdc
# XDC: The top module name and the constraint reference have the same name: 'camera_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/dave/ip/examples/ov13850_demo/ov13850_demo.srcs/sources_1/ip/camera_pll_1/camera_pll_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'camera_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
